### ISSUE TITLE
Freezes while saving on W10 x64

### ISSUE THREAD

**Issue by kross-uk** [Aries85/LightZone#216] opened 2018-01-05 13:50 UTC
Hi,

Every time I click save after my changes, it freezes and the only way to then close it is via task manager.
I'm running LZ 4.1.8 on Windows 10 x64, and LZ freezes after any type of change, any type of image.
I've tried uninstalling and reinstalling to no avail.
I've searched this forum but could only find existing threads on Ubuntu, so I submitted this ticket.

Hopefully you will have an idea of how to overcome this.
![lightzone settings](https://user-images.githubusercontent.com/35140704/34611869-2edfc7de-f21f-11e7-8a0f-6cc301ac53ce.png)

**Comment by ktgw0316** [comment] 2018-01-05 14:47
I think this issue is duplicate of #210. I've just changed the title of #210 to include not only Ubuntu but also Windows.

**Comment by kross-uk** [comment] 2018-01-05 15:16
Thank you for that.
Hopefully this will be resolved soon.
I have to confess I went to Rawtherapee in the meantime as a stopgap, but
would rather go back to LightZone when it works OK.

Kind regards,

Nuno Mendonca

**Comment by ktgw0316** [comment] 2018-01-11 14:36
You can download and try the latest package "LightZone-Installer-4.1.8-20180105-64bit.exe" from release page (https://github.com/ktgw0316/LightZone/releases/tag/4.1.8). If that does not work, feel free to reopen this issue.

**Closed by ktgw0316** 2018-01-11 14:36 UTC
Labels: duplicate
