### ISSUE TITLE
4.1.8 becomes unresponsive

### ISSUE THREAD

**Issue by daved163g** [Aries85/LightZone#214] opened 2018-01-02 21:59 UTC
Installed LightZone-Installer-4.1.8-20171226-amd64.exe a few days ago. Everything seemed to work OK. Did a few test edits, no problems. 

Came to use 4.1.8 again this week and found that the whole UI becomes unresponsive when I switch from Browse to Edit mode.  The window can be selected and it can be minimised and maximised but not closed.  No controls work, not even the styles browser. 
Sometimes the selected image will load in the edit window and sometimes it wont, leaving just 1 notch on the progress bar. How far the image load gets seems to depend on how long I leave LZ in Browse mode prior to selecting Edit mode. If I leave it a few seconds untils the CPU has quietened down then the image loads and the UI freezes a second or so later. If I select Edit mode immediately then the image fails to load.
The CPU goes from a quiescent 2% to a stready 25% and stays there doing nothing until the LightZone process is killed. There are no errors in the system error logs.

The only system "change" was that I had checked if there was an update for my video driver (nVidia Quadro 3450) and it appeared to do an upgrade (it reset all the windows back to VGA size). I tried rolling back to the previous driver but the problem with LZ persists. The previous driver (as rolled back) and the current one have the same version (9.18) which is a puzzle. The "new" driver seemed a little more sluggish than the old one. I will re-install an older driver when I get the chance and see if that helps.

**Comment by daved163g** [comment] 2018-01-03 16:02
UPDATE
I have tried an old video driver, I have deleted and reinstalled v4.18, I have reinstalled 4.1.7 and then upgraded that to v4.1.8. I have deleted software I installed since the problem [seemed to] started (SyncIOS, as it happens). I have returned to the latest video driver. All these actions had no effect. There are still no system error messages.

HOWEVER
I have found that it is only when the mouse moves into the Styles list in the Edit mode window that LZ freezes. Mouse movement anywhere else does not cause a problem. All controls work OK. You can even select a style from the menu and run it. You can even use the mouse to scroll the style list, as long as you keep within the confines of the vertical scroll bar. The CPU always returns to idle (1-2%) after any action.

BUT
As soon as the mouse hits the style list the CPU goes from idle to roughly 25% and stays there. The UI is unresponsive. LZ must be killed via Task Manager.

**Comment by ktgw0316** [comment] 2018-01-05 13:25
This issue seems to be a duplicate of #210.

**Comment by daved163g** [comment] 2018-01-06 20:00
Fixed in LightZone-Installer-4.1.8-20180105-64bit. Thank you.

**Closed** 2018-01-06 20:00 UTC
Labels: duplicate
